package main

import (
	"context"
	"errors"
	"fmt"
	"io"

	"github.com/spf13/cobra"

	"github.com/ystsbry/revu/internal/claude"
	"github.com/ystsbry/revu/internal/codex"
	"github.com/ystsbry/revu/internal/store"
)

func newResumeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resume [dir]",
		Short: "Resume the agent session that generated a review",
		Long: `Resume the agent session recorded in a review's review.yml by execing
` + "`claude --resume <session-id>`" + ` or ` + "`codex resume <session-id>`" + `,
dropping you into the agent's interactive TUI on the same conversation
that produced the review. The runtime is picked by review.yml's
` + "`generated_by.tool`" + ` field.

If [dir] is omitted, the reviewed pr-N directories under
~/.revu/{owner}/{repo}/ are listed in a picker so you can choose which one
to resume. The repo is derived from the current git remote.

Errors out if the selected review has no recorded session_id (e.g. it was
generated by an older revu that did not persist it).`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			var dir string
			if len(args) == 1 {
				resolved, err := store.ResolveReviewDir(args[0])
				if err != nil {
					return err
				}
				dir = resolved
			} else {
				picked, err := pickReviewedPRDir(cmd)
				if err != nil {
					return err
				}
				if picked == "" {
					return nil // user cancelled
				}
				dir = picked
			}

			r, err := store.Load(dir)
			if err != nil {
				return err
			}
			if r.GeneratedBy.SessionID == "" {
				return fmt.Errorf("review at %s has no recorded session_id; re-run `revu review` to capture one", dir)
			}

			return resumeAgent(cmd.Context(), cmd.OutOrStdout(), cmd.ErrOrStderr(), r.GeneratedBy.Tool, r.GeneratedBy.SessionID, r.PR.Repo, r.PR.Number)
		},
	}
	return cmd
}

// resumeAgent picks the right CLI based on the tool name recorded in
// review.yml and execs its resume command. tool names other than "codex"
// fall back to claude — the historical default and what older review.yml
// files (pre-codex support) record.
func resumeAgent(ctx context.Context, stdout, stderr io.Writer, tool, sessionID, repo string, prNumber int) error {
	switch tool {
	case "codex":
		fmt.Fprintf(stdout, "Resuming codex session %s for %s#%d ...\n\n", sessionID, repo, prNumber)
		err := codex.RunResume(ctx, codex.ResumeArgs{SessionID: sessionID})
		if errors.Is(err, codex.ErrCLINotFound) {
			fmt.Fprintln(stderr, codex.InstallHint())
		}
		return err
	default:
		fmt.Fprintf(stdout, "Resuming claude session %s for %s#%d ...\n\n", sessionID, repo, prNumber)
		err := claude.RunResume(ctx, claude.ResumeArgs{SessionID: sessionID})
		if errors.Is(err, claude.ErrCLINotFound) {
			fmt.Fprintln(stderr, claude.InstallHint())
		}
		return err
	}
}
