package main

import (
	"errors"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/ystsbry/revu/internal/claude"
	"github.com/ystsbry/revu/internal/store"
)

func newResumeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resume [dir]",
		Short: "Resume the claude session that generated a review",
		Long: `Resume the claude session recorded in a review's review.yml by execing
` + "`claude --resume <session-id>`" + `, dropping you into claude's interactive
TUI on the same conversation that produced the review.

If [dir] is omitted, the reviewed pr-N directories under
~/.revu/{owner}/{repo}/ are listed in a picker so you can choose which one
to resume. The repo is derived from the current git remote.

Errors out if the selected review has no recorded session_id (e.g. it was
generated by an older revu that did not persist it).`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			var dir string
			if len(args) == 1 {
				resolved, err := store.ResolveReviewDir(args[0])
				if err != nil {
					return err
				}
				dir = resolved
			} else {
				picked, err := pickReviewedPRDir(cmd)
				if err != nil {
					return err
				}
				if picked == "" {
					return nil // user cancelled
				}
				dir = picked
			}

			r, err := store.Load(dir)
			if err != nil {
				return err
			}
			if r.GeneratedBy.SessionID == "" {
				return fmt.Errorf("review at %s has no recorded session_id; re-run `revu review` to capture one", dir)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Resuming claude session %s for %s#%d ...\n\n", r.GeneratedBy.SessionID, r.PR.Repo, r.PR.Number)
			err = claude.RunResume(cmd.Context(), claude.ResumeArgs{SessionID: r.GeneratedBy.SessionID})
			if errors.Is(err, claude.ErrCLINotFound) {
				fmt.Fprintln(cmd.ErrOrStderr(), claude.InstallHint())
			}
			return err
		},
	}
	return cmd
}
