package main

import (
	"errors"
	"fmt"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/ystsbry/revu/internal/claude"
	"github.com/ystsbry/revu/internal/github"
	"github.com/ystsbry/revu/internal/store"
	"github.com/ystsbry/revu/internal/tui/picker"
)

func newReviewCmd() *cobra.Command {
	var focus string
	var repoRootFlag string
	cmd := &cobra.Command{
		Use:   "review [PR_NUMBER]",
		Short: "Generate a Claude review for a PR and open it in the TUI",
		Long: `Generate a review via the review-pr skill and open it in the TUI.

Without an argument, fetches PRs awaiting your review (gh's
"review-requested:@me" search) in the cwd's repository and shows a picker.

With an argument, treats it as the PR number and skips the picker.

The review is generated by invoking the local "claude" CLI in the
foreground with the /review-pr skill; its progress streams to your
terminal. When generation finishes, revu opens the resulting review
directory the same way as "revu open".`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()

			slug, err := store.CurrentRepoSlug()
			if err != nil {
				return fmt.Errorf("resolve cwd repo: %w (run revu review inside a git clone)", err)
			}

			var prNumber int
			if len(args) == 1 {
				n, err := strconv.Atoi(args[0])
				if err != nil || n <= 0 {
					return fmt.Errorf("PR_NUMBER must be a positive integer, got %q", args[0])
				}
				prNumber = n
			} else {
				gh := github.New()
				items, err := gh.ListReviewRequestedPRs(ctx)
				if err != nil {
					return err
				}
				if len(items) == 0 {
					fmt.Fprintln(cmd.OutOrStdout(), "No open PRs are awaiting your review in this repository.")
					return nil
				}
				picked, err := picker.Pick(items)
				if err != nil {
					return err
				}
				if picked == nil {
					fmt.Fprintln(cmd.OutOrStdout(), "Cancelled.")
					return nil
				}
				prNumber = picked.Number
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Generating review for %s#%d via claude --print /review-pr ...\n\n", slug, prNumber)

			outDir, err := claude.RunReviewPR(ctx, claude.ReviewArgs{
				PRNumber:  prNumber,
				Focus:     focus,
				OwnerRepo: slug,
			})
			if err != nil {
				if errors.Is(err, claude.ErrCLINotFound) {
					fmt.Fprintln(cmd.ErrOrStderr(), claude.InstallHint())
					return err
				}
				return err
			}

			fmt.Fprintf(cmd.OutOrStdout(), "\nReview generated at %s\nOpening...\n\n", outDir)
			return openReviewDir(outDir, repoRootFlag)
		},
	}
	cmd.Flags().StringVar(&focus, "focus", "", "categories to focus on, passed through to /review-pr (e.g. \"security,perf\")")
	cmd.Flags().StringVar(&repoRootFlag, "repo-root", "",
		"path to the local clone (skips cwd verification when set)")
	return cmd
}
